name: Deploy Flask app

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2.3.2
      with:
        python-version: '3.x'    
    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt
    - name: Start Flask app
      run: |
        source env/bin/activate
        gunicorn app:app --bind 0.0.0.0 &
        wait $!
    - name: print_ip 
      run: echo ${{ runner.ip }}
  
  tunneling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
      - name: Start ngrok tunnel
        run: |
          ./ngrok http 5000 > /dev/null &
          sleep 5
      - name: Print ngrok URL
        run: |
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
